### ISSUE TITLE
Remine 4 

### ISSUE THREAD

**Issue by mkastenmueller** [ozguryazilimas/redmine_toggl#1]
Hi everyone,

I upgraded to redmine 4, which is not supported by redmine_toggl.
Is a support for redmine 4 planned for the next time?

Would be nice, if I could use the plugin again ;)

**Comment by zaburt** [comment]
Hi @axxano, thank you for the report. Since Redmine 4 is relatively new, compatibility with Redmine 4 was not high priority. Since there is request for it, will do Redmine 4 port.

**Comment by mkastenmueller** [comment]
Thats great! Thanks

**Comment by zaburt** [comment]
Just finished some changes to the code to make it work with both Redmine 4 (tested on 4.0.2) and Redmine 3 (tested on 3.4.9), that should do it.

**Comment by zaburt** [comment]
Closing this issue as we are Redmine 4 compatible now, if there are other problems with the latest code we can look into them in another issue entry.
