### ISSUE TITLE
Error when bundle install

### ISSUE THREAD

**Issue by mepoohsta** [ozguryazilimas/redmine_toggl#2]
Installing oj 3.7.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/usr/share/redmine/vendor/cache/ruby/2.4.0/gems/oj-3.7.10/ext/oj
/usr/local/rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20190317-32384-1wct7lm.rb
extconf.rb
Cannot allocate memory - /usr/local/rvm/rubies/ruby-2.4.1/bin/ruby -r
./siteconf20190317-32384-1wct7lm.rb extconf.rb 2>&1

Gem files will remain installed in
/usr/share/redmine/vendor/cache/ruby/2.4.0/gems/oj-3.7.10 for inspection.
Results logged to
/usr/share/redmine/vendor/cache/ruby/2.4.0/extensions/x86_64-linux/2.4.0/oj-3.7.10/gem_make.out

An error occurred while installing oj (3.7.10), and Bundler cannot
continue.
Make sure that `gem install oj -v '3.7.10' --source 'https://rubygems.org/'`
succeeds before bundling.

**Comment by zaburt** [comment]
The environment you are running bundler does not have enough memory to compile oj gem, I would suggest stopping other running apps during bundle installation or increase available RAM to fix the issue. See this line from the output

    Cannot allocate memory - /usr/local/rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20190317-32384-1wct7lm.rb extconf.rb 2>&1
