### ISSUE TITLE
Sync error due empty activity for entries without tags

### ISSUE THREAD

**Issue by istamendil** [ozguryazilimas/redmine_toggl#6]
Hello!
First of all I would like to say thank you for such usefull plugin for toggl users! I've been using this plugin for quite some time already.

Today I had to reinstall redmine. I installed stable 4.2.0. Previously I successfully used some 3.* version. But that time I got error on toggle entries syncing: 

`ERROR FOR USER: ist MESSAGE: Validation failed: Activity cannot be blank TOGGL_ENTRY: {"guid"=>"...", "wid"=>..., "pid"=>..., "billable"=>false, "start"=>"2021-04-19T17:51:33+00:00", "stop"=>"2021-04-19T17:52:50+00:00", "duration"=>77, "description"=>"#3 Test entry", "at"=>"2021-04-19T17:51:59+00:00", "uid"=>..., "toggl_id"=>..., "user_id"=>5, "toggl_tags"=>[]}`

As I understood my Toggle time entries doesn't have any tags, Redmine validates Entry entity for activity is not equal to null. In lib/redmine_toggl.rb there is function activity_for_tags(tags) with the first line "return nil if tags.blank?". I suppose we need some default value here instead of nil.

However may be I dont understand something about Redmine ot your plugin. Also I'm not good in RoR. So sorry if that's my misunderstanding. If so please consider to explain what setting should I change to use your plugin without toggle tags for every entry. Thank you!

**Comment by zaburt** [comment]
Hello, glad you like this plugin ! I suspect you are missing some steps in your Redmine configuration. When you want to track "issue spent hours" you need to have at least one (default) time entry activity configured in your system. You can see the settings here Administration > Enumerations > Activities (time tracking) . Also see here for example https://www.redmine.org/boards/1/topics/54261 .

Redming Toggl can assign different activities by using the tags yes, but tags can be empty it is ok. If there is no tag to use, Redmine uses the default activity and you are missing that. If setting default activity does not fix it it will be helpful to get the full backtrace in the logs for the error to see what is going on.

**Comment by istamendil** [comment]
Oh. That makes sense! Redmine haven't ask me to set up default option or I missed it somehow.

Thank you for such quick answer!
