### ISSUE TITLE
Switch to v9 Toggl API as v8 will be powered off soon

### ISSUE THREAD

**Issue by kepi** [ozguryazilimas/redmine_toggl#7]
Hello,

it looks like Toggl is phasing out support for v8 API and judging from `TOGGLE_API_BASE_URL` it looks like this project is using v8.

Time window is pretty short, as v8 would be turned off completely by May 23. I learned about it from colleague today, but looks like it has been announced year and half ago.

Here are relevant links:

* https://engineering.toggl.com/changes/2022/10/01/api-v8-deprecation/index.html
* https://engineering.toggl.com/docs/additional/v8_migration_guide/index.html

**Comment by zaburt** [comment]
Thank you for the details we are looking into it

**Comment by zaburt** [comment]
We have switched to API v9. The external gem is removed and all the connection is done with internal code. We may create a brand new gem for V9 api but the code at the moment handles all the tasks needed.
